encoder_training_config:
  device: cuda
  
  # 数据集
  raw_data_dir: 
    - D:/raw_data/
    - /root/autodl-tmp/
  use_sample_for_scaler_fitting: 47 # max=47
  val_set_ratio: 0.2
  
  # 自训练掩码
  total_mask_ratio: 0.40
  block_len: 40
  channel_mask_ratio: 0.2

  # Encoder 参数
  batch_size: 128
  num_workers: 8
  feat_dim: 15
  embed_dim: 256
  n_head: 8
  n_layers: 4
  dropout: 0.1

  # 优化器参数
  lr: 0.001
  weight_decay: 0.001

  epochs: 60
